### Create new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "qwedf123@asd.asd",
    "password": "123qwerty"
}

### Sign in as an existing user

POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "qwedf123@asd.asd",
    "password": "123qwerty"
}

### Get the curr user

GET http://localhost:3000/auth/whoami

### Sign out

POST http://localhost:3000/auth/signout

### Find user by id

GET http://localhost:3000/auth/6


### Find all users by email

GET http://localhost:3000/auth?@email=@

### Update user

PATCH http://localhost:3000/auth/3
content-type: application/json

{ 
    "password": "brandnew@email.com"
}

### Delete user by id

DELETE http://localhost:3000/auth/3